import { AdminFrame } from "../../../components/admin/AdminFrame";
import { AdminGenerateDisclosure } from "../../../components/admin/AdminGenerateDisclosure";
import { AdminSheetWorkspace } from "../../../components/admin/AdminSheetWorkspace";
import { AreaCountsAction } from "../../../components/admin/AreaCountsAction";
import { OpsButton } from "../../../components/admin/OpsButton";
import { COMMAND_CENTER_COLUMNS } from "../../../lib/command-center-config";
import { loadEvergreenTab } from "../../../lib/command-center";

export const dynamic = "force-dynamic";

export default async function AdminEmailsPage() {
  const rows = await loadEvergreenTab("emails");

  return (
    <AdminFrame>
      <AdminSheetWorkspace
        tab="emails"
        heroTitle="Emails"
        heroDescription={
          <p>Promotional emails are generated by content area counts. Subject lines are generated after content is drafted.</p>
        }
        editorTitle="Emails Evergreen"
        columns={[...COMMAND_CENTER_COLUMNS.emails]}
        initialRows={rows}
        dateColumn="Email_Publish_Date"
      >
        <div className="admin-action-stack admin-figma-action-stack">
          <div className="admin-ops-grid">
            <AdminGenerateDisclosure label="Generate New Emails">
              <AreaCountsAction action="generate_new_emails" label="Generate new emails" mode="counts" />
            </AdminGenerateDisclosure>
            <OpsButton action="generate_email_subjects" label="Generate Subjects" icon="refresh" variant="ghost" />
          </div>
        </div>
      </AdminSheetWorkspace>
    </AdminFrame>
  );
}
