import { AdminFrame } from "../../../components/admin/AdminFrame";
import { AreaCountsAction } from "../../../components/admin/AreaCountsAction";
import { DataSheetEditor } from "../../../components/admin/DataSheetEditor";
import { OpsButton } from "../../../components/admin/OpsButton";
import { COMMAND_CENTER_COLUMNS } from "../../../lib/command-center-config";
import { loadEvergreenTab } from "../../../lib/command-center";

export const dynamic = "force-dynamic";

export default async function AdminEmailsPage() {
  const rows = await loadEvergreenTab("emails");

  return (
    <AdminFrame>
      <section className="admin-panel admin-panel-hero">
        <p className="eyebrow admin-eyebrow">Emails</p>
        <h1>Emails</h1>
        <p>
          Promotional emails are generated by content area counts. Subject lines are generated after content is drafted.
        </p>
        <div className="admin-meta-row">
          <span className="admin-meta-pill">Area-led segmentation</span>
          <span className="admin-meta-pill">No dash-heavy copy</span>
        </div>
        <div className="admin-action-stack">
          <AreaCountsAction action="generate_new_emails" label="Generate new emails" mode="counts" />
          <div className="admin-actions-inline">
            <OpsButton action="generate_email_subjects" label="Generate email subjects" />
          </div>
        </div>
      </section>

      <DataSheetEditor
        tab="emails"
        title="Emails Evergreen"
        columns={[...COMMAND_CENTER_COLUMNS.emails]}
        initialRows={rows}
        dateColumn="Email_Publish_Date"
      />
    </AdminFrame>
  );
}
